apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: atc-developer
  namespace: testns
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]