apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-service
  namespace: web
spec:
  selector:
    service: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  