apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  namespace: web
spec:
  selector:
    service: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort  